    drop table Category if exists;

    drop table CategoryPolicyRuleMapping if exists;

    drop table CategoryPolicyRuleMapping_AUD if exists;

    drop table Category_AUD if exists;

    drop table CurrencyConversion if exists;

    drop table Expense if exists;

    drop table Expense_AUD if exists;

    drop table PolicyRule if exists;

    drop table PolicyRule_AUD if exists;

    drop table REVINFO if exists;

    create table Category (
        categoryType varchar(20) not null,
        id bigint generated by default as identity (start with 1),
        name varchar(255),
        primary key (id)
    );

    create table CategoryPolicyRuleMapping (
        categoryId bigint not null,
        ruleId bigint not null,
        unique (ruleId)
    );

    create table CategoryPolicyRuleMapping_AUD (
        REV integer not null,
        categoryId bigint not null,
        ruleId bigint not null,
        REVTYPE tinyint,
        primary key (REV, categoryId, ruleId)
    );

    create table Category_AUD (
        categoryType varchar(20) not null,
        id bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        name varchar(255),
        primary key (id, REV)
    );

    create table CurrencyConversion (
        id bigint generated by default as identity (start with 1),
        conversionDate date,
        original varchar(255),
        rate numeric(19,2),
        wanted varchar(255),
        primary key (id)
    );

    create table Expense (
        id bigint generated by default as identity (start with 1),
        endDate date,
        amount numeric(19,2),
        currency varchar(255),
        name varchar(255),
        startDate date,
        transactionDate timestamp,
        vendor varchar(255),
        categoryId bigint not null,
        primary key (id)
    );

    create table Expense_AUD (
        id bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        endDate date,
        amount numeric(19,2),
        currency varchar(255),
        name varchar(255),
        startDate date,
        transactionDate timestamp,
        vendor varchar(255),
        categoryId bigint,
        primary key (id, REV)
    );

    create table PolicyRule (
        name varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        active boolean not null,
        endDate date,
        ruleValue varchar(255),
        startDate date,
        stopType varchar(255),
        primary key (id)
    );

    create table PolicyRule_AUD (
        name varchar(31) not null,
        id bigint not null,
        REV integer not null,
        REVTYPE tinyint,
        active boolean,
        endDate date,
        ruleValue varchar(255),
        startDate date,
        stopType varchar(255),
        primary key (id, REV)
    );

    create table REVINFO (
        REV integer generated by default as identity (start with 1),
        REVTSTMP bigint,
        primary key (REV)
    );

    alter table CategoryPolicyRuleMapping 
        add constraint FKAA2D7422896685AC 
        foreign key (ruleId) 
        references PolicyRule;

    alter table CategoryPolicyRuleMapping 
        add constraint FKAA2D74224D31CE9E 
        foreign key (categoryId) 
        references Category;

    alter table CategoryPolicyRuleMapping_AUD 
        add constraint FK305EC0F3DF74E053 
        foreign key (REV) 
        references REVINFO;

    alter table Category_AUD 
        add constraint FK23378FEFDF74E053 
        foreign key (REV) 
        references REVINFO;

    alter table Expense 
        add constraint FK152D60384D31CE9E 
        foreign key (categoryId) 
        references Category;

    alter table Expense_AUD 
        add constraint FK2BEB209DF74E053 
        foreign key (REV) 
        references REVINFO;

    alter table PolicyRule_AUD 
        add constraint FKEFD6A3FDF74E053 
        foreign key (REV) 
        references REVINFO;
